apiVersion: v1
kind: PersistentVolume
metadata:
  name: reg-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 100Gi
  nfs:
    server: 10.10.10.3
    path: /mnt/Openshift/registry
  persistentVolumeReclaimPolicy: Recycle
