apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "reg-claim"
  namespace: openshift-image-registry
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
