apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 20Gi
  nfs:
    server: 10.10.10.3
    path: /mnt/Openshift/mysql
  persistentVolumeReclaimPolicy: Recycle

