apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress:5.6
        resources:
          requests:
            memory: "500Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
        env:
        - name: WORDPRESS_DB_HOST
          value: <clusterip> # 같은 pod내에 있으면 동일 ip라서 상관없다.
        - name: WORDPRESS_DB_NAME
          value: reca3
        - name: WORDPRESS_DB_USER
          value: mysqluser
        - name: WORDPRESS_DB_PASSWORD
          value: redhat
        ports:
        - containerPort: 8080
